# General
title: Douglas Medeiros
email: eu@douglasmedeiros.dev
description: Links do Douglas Medeiros - Software Engineer @ PicPay | Engenheiro de Software | Apaixonado por Tecnologia e Inovação
source: .
destination: ./public
baseurl: ""
url: https://links.douglasmedeiros.dev
srcurl: ""
lang: pt-BR
locale: pt_BR
author: Douglas Medeiros
google_analytics: "" # UA-111111111-1
published: true

# Social Media
social:
  name: Douglas Medeiros
  links:
    - https://www.instagram.com/douglasmedeiros.dev/
    - https://bsky.app/profile/douglasmedeiros.dev
    - https://github.com/medeirosinacio
    - https://www.linkedin.com/in/medeirosinacio/
type: links
keywords: Douglas Medeiros, Douglas, Medeiros, Software, Engenheiro, PicPay, Links, Instagram, Twitter, LinkedIn, GitHub

# Site Paths
post_path: /assets/images/posts/
icon_path: /assets/icons/
image_path: /assets/images/
css_path: /assets/css/
js_path: /assets/scripts/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - app
  - .idea
  - server.sh
  - LICENSE
